### PR TITLE
Add boolean flag to support copyright as first line

### PR DESCRIPTION
**Pull request by krishnamiriyala**

### CODE REVIEW

**Review by shaunschembri — APPROVED** [review]
LGTM

**Comment by krishnamiriyala** [comment]
I have signed the CLA but the pull request doesn't seem to get updated and the failures doesn't seem to be related to my PR. Any help?
@elasticmachine
beats-ci/pr-merge — The build of this commit was aborted
Required
[Details](https://beats-ci.elastic.co/job/Library/job/go-licenser-mbp/job/PR-58/1/display/redirect)
@cla-checker-service
CLA — Author of some commits did not sign a contributor agreement
[Details](https://www.elastic.co/contributor-agreement)

continuous-integration/appveyor/pr — AppVeyor build failed
[Details](https://ci.appveyor.com/project/marclop/go-licenser/builds/45924257)

**Comment by krishnamiriyala** [comment]
@shaunschembri  would you be able to merge this?

**Comment by shaunschembri** [comment]
@krishnamiriyala Seems CI has some problems, but your code looks good so I merged it. Thanks for the contribution

**Pull request merged**
