### PR TITLE
build: bump go version to 1.17

### PR DESCRIPTION
**Pull request by kruskall**
Remove deprecated GO111MODULE env variable and replace old go install
with the new 'go run module@version' syntax.
The new makefile is leaner and we can remove dependencies from go.mod
making the app truly 'zero dependency' as advertised.

Blocked by https://github.com/elastic/go-licenser/pull/52
Blocked by https://github.com/elastic/go-licenser/pull/51
Blocked by https://github.com/elastic/go-licenser/pull/50

### CODE REVIEW

**Review by marclop — COMMENTED** [review]
Mostly looks good. Can you look at the 1.17 build failures and address those? I think most of the failures have to do with using legacy Go build tags and the new build tags missing.

**Comment by kruskall** [comment]
The failures in the 1.17 job should be fixed once https://github.com/elastic/go-licenser/pull/51 is merged

**Comment by marclop** [comment]
@kruskall the linters that are run in this PR (`staticcheck`) are different from the ones that run in that one since it's using the old linters. That's why I suggested that we fix the errors here since the new linter is causing the failures.

**Comment by kruskall** [comment]
I've added the commits from the other PRs and the pipeline is green. 

As a positive note, the licenser should now suppot Go 1.17 new build lines instead of replacing them with the license header.

**Review by marclop — APPROVED** [review]

**Pull request merged**
